"""Add user avatars and location metadata for Stitch design

Revision ID: 3ddb932c27b5
Revises: 63d706c2a348
Create Date: 2026-09-21 22:50:49.383627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ddb932c27b5'
down_revision = '63d706c2a348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hero_image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('emoji', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False, server_default='0'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_verified')
        batch_op.drop_column('bio')
        batch_op.drop_column('avatar_url')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('is_verified')
        batch_op.drop_column('emoji')
        batch_op.drop_column('rating')
        batch_op.drop_column('description')
        batch_op.drop_column('hero_image_url')

    # ### end Alembic commands ###
