"""add location provider identity

Revision ID: 822fa90ed935
Revises: b0827dabfbae
Create Date: 2026-09-15 03:06:41.853069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822fa90ed935'
down_revision = 'b0827dabfbae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('provider_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('provider_id')
        batch_op.drop_column('provider')

    # ### end Alembic commands ###
