"""Remove country relationship from posts

Revision ID: b0827dabfbae
Revises: 76ddda8afaf6
Create Date: 2026-09-13 20:51:12.940747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0827dabfbae'
down_revision = '76ddda8afaf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('country_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'country', ['country_id'], ['id'])

    # ### end Alembic commands ###
